#!/usr/bin/env python3
"""Build Task I table/figure artifacts for Exp.tex."""
from __future__ import annotations

import csv
import json
import math
import os
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
FIGURES = ROOT / "figures"
SECTIONS = ROOT / "sections"

def _resolve_run() -> Path:
    configured = os.environ.get("DEXPOSURE_TASK1_RUN")
    if configured:
        return Path(configured)
    return RESULTS / "latest"


def _load(path: Path) -> dict:
    return json.loads(path.read_text())


def _mean(xs: list[float]) -> float:
    return float(np.mean(xs)) if xs else float("nan")


def _fmt(v: float | None, nd: int = 3) -> str:
    if v is None:
        return "N/A"
    if isinstance(v, float) and math.isnan(v):
        return "N/A"
    return f"{v:.{nd}f}"


def build_summary() -> dict:
    run = _resolve_run()
    if not run.exists():
        raise FileNotFoundError(
            f"Task I run directory not found: {run}. Set DEXPOSURE_TASK1_RUN "
            "or run scripts/run_benchmarks_sequential.py first."
        )

    b1_c0 = _load(run / "b1_forecast__m5_fm_rules.json")["results"]
    b1_c2 = _load(run / "b1_forecast__m1_persistence_rules.json")["results"]
    b2_h0 = _load(run / "b2_warning__h1_weighted_degree.json")["results"]
    b3_c0 = _load(run / "b3_calibration__m5_fm_rules.json")["results"][0]
    b6_c0 = _load(run / "b6_robustness__m5_fm_rules.json")["results"]
    b6_c2 = _load(run / "b6_robustness__m1_persistence_rules.json")["results"]

    def pick_h4(rows: list[dict]) -> dict:
        return next(r for r in rows if int(r["horizon"]) == 4)

    b1_c0_h4 = pick_h4(b1_c0)
    b1_c2_h4 = pick_h4(b1_c2)

    out = {
        "m5_fm_rules": {
            "b1_rank_corr_h4": b1_c0_h4["rank_correlation"],
            "b1_trend_consistency_h4": b1_c0_h4["trend_consistency"],
            "b1_hhi_mae_h4": b1_c0_h4["hhi_mae"],
            "b2_precision_mean": _mean([r["precision"] for r in b2_h0]),
            "b2_f1_mean": _mean([r["f1_warning"] for r in b2_h0]),
            "b2_lead_time_mean": _mean([r["lead_time_weeks"] for r in b2_h0]),
            "b3_ece": b3_c0["ece"],
            "b3_pi_coverage": b3_c0["pi_coverage"],
            "b3_crps": b3_c0["crps"],
            "b6_relative_degradation_mean": _mean([r["relative_degradation"] for r in b6_c0]),
        },
        "m1_persistence_rules": {
            "b1_rank_corr_h4": b1_c2_h4["rank_correlation"],
            "b1_trend_consistency_h4": b1_c2_h4["trend_consistency"],
            "b1_hhi_mae_h4": b1_c2_h4["hhi_mae"],
            "b2_precision_mean": None,
            "b2_f1_mean": None,
            "b2_lead_time_mean": None,
            "b3_ece": None,
            "b3_pi_coverage": None,
            "b3_crps": None,
            "b6_relative_degradation_mean": _mean([r["relative_degradation"] for r in b6_c2]),
        },
    }
    return out


def write_table(summary: dict) -> None:
    out_json = RESULTS / "paper_task1_latest.json"
    out_csv = RESULTS / "paper_task1_latest.csv"
    out_tex = SECTIONS / "Table_TaskI_Summary.tex"

    out_json.write_text(json.dumps(summary, indent=2))

    cols = ["method"] + list(summary["m5_fm_rules"].keys())
    with out_csv.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=cols)
        writer.writeheader()
        for m in ["m5_fm_rules", "m1_persistence_rules"]:
            row = {"method": m}
            row.update(summary[m])
            writer.writerow(row)

    c0 = summary["m5_fm_rules"]
    c2 = summary["m1_persistence_rules"]
    tex = [
        "% Auto-generated by scripts/build_task1_artifacts.py",
        "\\begin{table*}[!htbp]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Metric (Task I) & \\texttt{m5\\_fm\\_rules} (FM) & \\texttt{m1\\_persistence\\_rules} (Persistence) \\\\",
        "\\midrule",
        f"\\texttt{{b1\\_forecast}} RankCorr@h4 & {_fmt(c0['b1_rank_corr_h4'])} & {_fmt(c2['b1_rank_corr_h4'])} \\\\",
        f"\\texttt{{b1\\_forecast}} TrendCons@h4 & {_fmt(c0['b1_trend_consistency_h4'])} & {_fmt(c2['b1_trend_consistency_h4'])} \\\\",
        f"\\texttt{{b1\\_forecast}} HHI-MAE@h4 (lower better) & {_fmt(c0['b1_hhi_mae_h4'])} & {_fmt(c2['b1_hhi_mae_h4'])} \\\\",
        f"\\texttt{{b2\\_warning}} Precision (\\texttt{{h1\\_weighted\\_degree}} mean) & {_fmt(c0['b2_precision_mean'])} & N/A \\\\",
        f"\\texttt{{b2\\_warning}} F1-warning (\\texttt{{h1\\_weighted\\_degree}} mean) & {_fmt(c0['b2_f1_mean'])} & N/A \\\\",
        f"\\texttt{{b2\\_warning}} Lead time (\\texttt{{h1\\_weighted\\_degree}} weeks) & {_fmt(c0['b2_lead_time_mean'])} & N/A \\\\",
        f"\\texttt{{b3\\_calibration}} ECE (\\texttt{{m5\\_fm\\_rules}} only) & {_fmt(c0['b3_ece'])} & N/A \\\\",
        f"\\texttt{{b3\\_calibration}} PI coverage (\\texttt{{m5\\_fm\\_rules}} only) & {_fmt(c0['b3_pi_coverage'])} & N/A \\\\",
        f"\\texttt{{b6\\_robustness}} Relative degradation (mean) & {_fmt(c0['b6_relative_degradation_mean'])} & {_fmt(c2['b6_relative_degradation_mean'])} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Task I evidence for deployable risk monitoring on the 2025 test split. The table is a numeric audit ledger; Fig.~\\ref{fig:task1_deployable_signal} compresses the same evidence into the main claim.}",
        "\\label{tab:task1_summary}",
        "\\end{table*}",
        "",
    ]
    out_tex.write_text("\n".join(tex))


def write_figure(summary: dict | None = None) -> None:
    """Render Fig. 5: FM deployable risk signal, not a rank-correlation repeat."""
    summary = summary or build_summary()
    fm = summary["m5_fm_rules"]
    persistence = summary["m1_persistence_rules"]

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 9.5,
            "figure.dpi": 300,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.05,
        }
    )
    fig, axes = plt.subplots(1, 3, figsize=(9.4, 3.25))
    colors = {"fm": "#4A6FA5", "persistence": "#8A939E", "accent": "#3A8E8C"}

    panels = [
        (
            axes[0],
            "Static rank is hard to beat",
            "RankCorr@h4 (higher better)",
            [fm["b1_rank_corr_h4"], persistence["b1_rank_corr_h4"]],
            ["FM", "Persist"],
            [colors["fm"], colors["persistence"]],
            (0.0, 0.65),
        ),
        (
            axes[1],
            "FM adds directional signal",
            "TrendCons@h4 (higher better)",
            [fm["b1_trend_consistency_h4"], persistence["b1_trend_consistency_h4"]],
            ["FM", "Persist"],
            [colors["fm"], colors["persistence"]],
            (0.0, 0.70),
        ),
        (
            axes[2],
            "FM improves deployability",
            "Robust degradation (lower better)",
            [
                fm["b6_relative_degradation_mean"],
                persistence["b6_relative_degradation_mean"],
            ],
            ["FM", "Persist"],
            [colors["fm"], colors["persistence"]],
            (0.0, 0.18),
        ),
    ]

    for ax, title, ylabel, values, labels, bar_colors, ylim in panels:
        x = np.arange(len(values))
        ax.bar(x, values, color=bar_colors, edgecolor="#222222", width=0.58)
        ax.set_title(title, fontsize=10, pad=7)
        ax.set_ylabel(ylabel)
        ax.set_xticks(x)
        ax.set_xticklabels(labels)
        ax.set_ylim(*ylim)
        ax.grid(axis="y", linestyle="--", alpha=0.3)
        for idx, value in enumerate(values):
            ax.text(
                idx,
                value + (ylim[1] - ylim[0]) * 0.035,
                f"{value:.3f}",
                ha="center",
                va="bottom",
                fontsize=8,
            )
    coverage = fm["b3_pi_coverage"]
    target = 0.90
    axes[2].text(
        0.03,
        0.96,
        f"PI coverage = {coverage:.3f} (target {target:.2f})",
        transform=axes[2].transAxes,
        ha="left",
        va="top",
        fontsize=7.8,
        bbox={"boxstyle": "round,pad=0.35", "facecolor": "#EEF7F4", "edgecolor": colors["accent"]},
    )

    fig.suptitle("Task I: FM Deployable Risk Signal", fontsize=13, y=1.05)
    fig.subplots_adjust(wspace=0.34)

    FIGURES.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIGURES / "fig5_task1_deployable_signal.png", format="png")
    fig.savefig(FIGURES / "fig5_task1_deployable_signal.pdf", format="pdf")
    plt.close(fig)


def main() -> None:
    summary = build_summary()
    write_table(summary)
    write_figure(summary)
    print("Wrote:")
    print(f"- {RESULTS / 'paper_task1_latest.json'}")
    print(f"- {RESULTS / 'paper_task1_latest.csv'}")
    print(f"- {SECTIONS / 'Table_TaskI_Summary.tex'}")
    print(f"- {FIGURES / 'fig5_task1_deployable_signal.png'}")
    print(f"- {FIGURES / 'fig5_task1_deployable_signal.pdf'}")


if __name__ == "__main__":
    main()
