#!/usr/bin/env python3
"""Build Task I table/figure artifacts for Exp.tex."""
from __future__ import annotations

import csv
import json
import math
import os
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
FIGURES = ROOT / "figures"
SECTIONS = ROOT / "sections"

def _resolve_run() -> Path:
    configured = os.environ.get("DEXPOSURE_TASK1_RUN")
    if configured:
        return Path(configured)
    return RESULTS / "latest"


def _load(path: Path) -> dict:
    return json.loads(path.read_text())


def _mean(xs: list[float]) -> float:
    return float(np.mean(xs)) if xs else float("nan")


def _fmt(v: float | None, nd: int = 3) -> str:
    if v is None:
        return "N/A"
    if isinstance(v, float) and math.isnan(v):
        return "N/A"
    return f"{v:.{nd}f}"


def build_summary() -> dict:
    run = _resolve_run()
    if not run.exists():
        raise FileNotFoundError(
            f"Task I run directory not found: {run}. Set DEXPOSURE_TASK1_RUN "
            "or run scripts/run_benchmarks_sequential.py first."
        )

    b1_c0 = _load(run / "b1_forecast__m5_fm_rules.json")["results"]
    b1_c2 = _load(run / "b1_forecast__m1_persistence_rules.json")["results"]
    b2_h0 = _load(run / "b2_warning__h1_weighted_degree.json")["results"]
    b3_c0 = _load(run / "b3_calibration__m5_fm_rules.json")["results"][0]
    b6_c0 = _load(run / "b6_robustness__m5_fm_rules.json")["results"]
    b6_c2 = _load(run / "b6_robustness__m1_persistence_rules.json")["results"]

    def pick_h4(rows: list[dict]) -> dict:
        return next(r for r in rows if int(r["horizon"]) == 4)

    b1_c0_h4 = pick_h4(b1_c0)
    b1_c2_h4 = pick_h4(b1_c2)

    out = {
        "m5_fm_rules": {
            "b1_rank_corr_h4": b1_c0_h4["rank_correlation"],
            "b1_trend_consistency_h4": b1_c0_h4["trend_consistency"],
            "b1_hhi_mae_h4": b1_c0_h4["hhi_mae"],
            "b2_precision_mean": _mean([r["precision"] for r in b2_h0]),
            "b2_f1_mean": _mean([r["f1_warning"] for r in b2_h0]),
            "b2_lead_time_mean": _mean([r["lead_time_weeks"] for r in b2_h0]),
            "b3_ece": b3_c0["ece"],
            "b3_pi_coverage": b3_c0["pi_coverage"],
            "b3_crps": b3_c0["crps"],
            "b6_relative_degradation_mean": _mean([r["relative_degradation"] for r in b6_c0]),
        },
        "m1_persistence_rules": {
            "b1_rank_corr_h4": b1_c2_h4["rank_correlation"],
            "b1_trend_consistency_h4": b1_c2_h4["trend_consistency"],
            "b1_hhi_mae_h4": b1_c2_h4["hhi_mae"],
            "b2_precision_mean": None,
            "b2_f1_mean": None,
            "b2_lead_time_mean": None,
            "b3_ece": None,
            "b3_pi_coverage": None,
            "b3_crps": None,
            "b6_relative_degradation_mean": _mean([r["relative_degradation"] for r in b6_c2]),
        },
    }
    return out


def write_table(summary: dict) -> None:
    out_json = RESULTS / "paper_task1_latest.json"
    out_csv = RESULTS / "paper_task1_latest.csv"
    out_tex = SECTIONS / "Table_TaskI_Summary.tex"

    out_json.write_text(json.dumps(summary, indent=2))

    cols = ["method"] + list(summary["m5_fm_rules"].keys())
    with out_csv.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=cols)
        writer.writeheader()
        for m in ["m5_fm_rules", "m1_persistence_rules"]:
            row = {"method": m}
            row.update(summary[m])
            writer.writerow(row)

    c0 = summary["m5_fm_rules"]
    c2 = summary["m1_persistence_rules"]
    tex = [
        "% Auto-generated by scripts/build_task1_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Metric (Task I) & m5_fm_rules (FM) & m1_persistence_rules (Persistence) \\\\",
        "\\midrule",
        f"b1_forecast RankCorr@h4 & {_fmt(c0['b1_rank_corr_h4'])} & {_fmt(c2['b1_rank_corr_h4'])} \\\\",
        f"b1_forecast TrendCons@h4 & {_fmt(c0['b1_trend_consistency_h4'])} & {_fmt(c2['b1_trend_consistency_h4'])} \\\\",
        f"b1_forecast HHI-MAE@h4 (lower better) & {_fmt(c0['b1_hhi_mae_h4'])} & {_fmt(c2['b1_hhi_mae_h4'])} \\\\",
        f"b2_warning Precision (h1_weighted_degree mean) & {_fmt(c0['b2_precision_mean'])} & N/A \\\\",
        f"b2_warning F1-warning (h1_weighted_degree mean) & {_fmt(c0['b2_f1_mean'])} & N/A \\\\",
        f"b2_warning Lead time (h1_weighted_degree weeks) & {_fmt(c0['b2_lead_time_mean'])} & N/A \\\\",
        f"b3_calibration ECE (m5_fm_rules only) & {_fmt(c0['b3_ece'])} & N/A \\\\",
        f"b3_calibration PI coverage (m5_fm_rules only) & {_fmt(c0['b3_pi_coverage'])} & N/A \\\\",
        f"b6_robustness Relative degradation (mean) & {_fmt(c0['b6_relative_degradation_mean'])} & {_fmt(c2['b6_relative_degradation_mean'])} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Task I monitoring quality summary on the 2025 test split.}",
        "\\label{tab:task1_summary}",
        "\\end{table}",
        "",
    ]
    out_tex.write_text("\n".join(tex))


def write_figure() -> None:
    run = _resolve_run()
    b1_c0 = _load(run / "b1_forecast__m5_fm_rules.json")["results"]
    b1_c2 = _load(run / "b1_forecast__m1_persistence_rules.json")["results"]
    horizons = [int(r["horizon"]) for r in b1_c0]
    rc0 = [float(r["rank_correlation"]) for r in b1_c0]
    rc2 = [float(r["rank_correlation"]) for r in b1_c2]

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 10,
            "figure.dpi": 300,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.05,
        }
    )
    fig, ax = plt.subplots(figsize=(6.8, 4.0))
    ax.plot(horizons, rc0, marker="o", linewidth=2, color="#4A6FA5", label="m5_fm_rules (FM)")
    ax.plot(horizons, rc2, marker="s", linewidth=2, color="#6B7B8D", label="m1_persistence_rules (Persistence)")
    ax.set_xlabel("Forecast Horizon (weeks)")
    ax.set_ylabel("b1_forecast Rank Correlation")
    ax.set_title("Task I b1_forecast: Rank Correlation Across Horizons")
    ax.set_xticks(horizons)
    ax.set_ylim(0.45, 0.62)
    ax.grid(True, linestyle="--", alpha=0.35)
    ax.legend(frameon=False, loc="lower left")

    FIGURES.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIGURES / "fig5_task1_b1_rankcorr.png", format="png")
    fig.savefig(FIGURES / "fig5_task1_b1_rankcorr.pdf", format="pdf")
    plt.close(fig)


def main() -> None:
    summary = build_summary()
    write_table(summary)
    write_figure()
    print("Wrote:")
    print(f"- {RESULTS / 'paper_task1_latest.json'}")
    print(f"- {RESULTS / 'paper_task1_latest.csv'}")
    print(f"- {SECTIONS / 'Table_TaskI_Summary.tex'}")
    print(f"- {FIGURES / 'fig5_task1_b1_rankcorr.png'}")
    print(f"- {FIGURES / 'fig5_task1_b1_rankcorr.pdf'}")


if __name__ == "__main__":
    main()
