function = "bin.graphpfn_evaluate.main"
n_seeds = 1

[base_config]
amp = true
checkpoint_name = "graphpfn-v1"
unfreeze_all = true
n_steps = -1
epoch_size = 5
patience = 20
seq_len_pred = 1000
min_train_ratio = 0.5

[base_config.data]
cache = false
path = "data/"
setting = "transductive"
time_idx = 0
split_strategy = "temporal"
label_idx = 0
num_policy = "noisy-quantile-normal"

[base_config.data.graph_encodings]
preprocess = "standard"

[base_config.data.graph_encodings.lap_pe]
k = 10

[base_config.data.graph_encodings.degree]
log = true

[base_config.data.graph_encodings.pagerank]
log = true

[base_config.optimizer]
type = "AdamW"
lr = 0.0001
weight_decay = 0.0
